import math

#_____Настройки_____
WIDTH = 1200
HEIGHT = 800
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FIVE_HEIGHT = 5 * HEIGHT
TWO_HEIGHT = 2 * HEIGHT
BLOCK = 100
FPS = 60

#_____Настройки игрока_____
PLAYER_POSITION = (HALF_WIDTH // 4, HALF_HEIGHT + 300)
PLAYER_ANGLE = 0
PLAYER_MOVEMENT = 4

#_____Настройки рейкастинга_____
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = 300
MAX_DEPTH = 800
DELTA_ANGLE = FOV / NUM_RAYS
DIST = NUM_RAYS / (2 * math.tan(HALF_FOV))
PROJECTION_COEFFICIENT = 3 * DIST * BLOCK
FOV_SIZE = WIDTH // NUM_RAYS

#_____Настройки рейкастинга_____
DOUBLE_PI = math.pi * 2
CENTER_RAY = NUM_RAYS // 2 - 1
FAKE_RAYS = 100
FAKE_RAYS_RANGE = NUM_RAYS - 1 + 2 * FAKE_RAYS

#_____Настройки текстур_____
TEXTURE_WIDTH = 1200
TEXTURE_HEIGHT = 1200
TEXTURE_SCALE = TEXTURE_WIDTH // BLOCK

#_____Цвета_____
WHITE = (255, 255, 255)
FLOOR = (244, 164, 96)
